---
styleguide: sourcelevel/linters
engines:
  reek:
    enabled: true
  fixme:
    enabled: false
  rubocop:
    enabled: false
  brakeman:
    enabled: false
  duplication:
    enabled: false
  remark-lint:
    enabled: false
  bundler-audit:
    enabled: false
